language: node_js
before_install:
  - "npm install ./docker/frontend "
cache:
  directories:
    - "node_modules"

sudo: required
services:
  - docker
before_install:
  - cd ./docker/keras-color-svc
install:
  - docker build -t  keras-color-svc .
  - docker run -p 5000:5000 -d keras-color-svc
  - cd ..
  - cd node
  - docker build -t keras-node-svc .
  - docker run -p 8888:8888 -d  keras-node-svc
script:
  - docker ps | grep  keras-color-svc
  - docker ps | grep  keras-node-svc