apiVersion: v1
kind: Service
metadata:
  name: keras-color-svc
  labels:
    name: keras-color-svc
    app: demo
spec:
  selector:
    name: keras-color-svc
  type: NodePort
  ports:
   - port: 5000
     targetPort: 5000
     protocol: TCP