apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "colorize-web"
  namespace: "default"
  labels:
    app: "colorize-web"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "colorize-web"
  template:
    metadata:
      labels:
        app: "colorize-web"
    spec:
      containers:
      - name: "keras-node-svc"
        image: "telexine/keras-node-svc:latest"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "colorize-web"
  namespace: "default"
  labels:
    app: "colorize-web"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "colorize-web"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80



---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-23T11:57:22Z
  labels:
    app: colorize-web
  name: colorize-web-service
  namespace: default
  resourceVersion: "2591"
  selfLink: /api/v1/namespaces/default/services/colorize-web-service
  uid: cca26ca9-d6ba-11e8-97d9-42010a940068
spec:
  clusterIP: 10.96.0.22
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30174
    port: 8080
    protocol: TCP
    targetPort: 8888
  selector:
    app: colorize-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.240.243.117