apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keras-color-svc
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: keras-color-svc
        image: telexine/keras-color-svc:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: keras-color-svc
spec:
  type: LoadBalancer
  selector:
    app: keras-color-svc
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP