apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keras-node-svc
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: keras-node-svc
        image: telexine/keras-node-svc:latest
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: keras-node-svc
spec:
  type: LoadBalancer
  selector:
    app: keras-node-svc
  ports:
  - port: 8088