apiVersion: v1
kind: Service
metadata:
  name: keras-node-svc
  labels:
    name: keras-node-svc
    app: demo 
spec:
  selector:
    name: keras-node-svc
  type: NodePort
  ports:
   - port: 8888
     name: keras-node-svc
     targetPort: 8888
     protocol: TCP
