apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keras-vue-frontend
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: keras-vue-frontend
        image: \
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keras-vue-frontend
spec:
  type: LoadBalancer
  selector:
    app: keras-vue-frontend
  ports:
  - port: 8080